services:
  postgres:
    image: pgvector/pgvector:pg15
    # build:
      # dockerfile: postgres/Dockerfile
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_DATABASE:-n8n}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER:-postgres}'
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - DB_TYPE=${DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${DB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=${DB_PORT:-5432}
      - DB_POSTGRESDB_DATABASE=${DB_DATABASE:-n8n}
      - DB_POSTGRESDB_USER=${DB_USER:-postgres}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD:-changeme}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - N8N_BASE_URL=http://localhost:5678/
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_DATA_FOLDER=/home/node/.n8n
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168   # 7 дней
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none # Экономит кучу места. 'info' - компромисс
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false # <-- Исправлено на false для скорости!
      - NODE_OPTIONS=--max-old-space-size=2048
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - web
    depends_on:
      postgres:
        condition: service_healthy

  embedding-service:
    build: ./embedding-service
    networks:
      - web
    ports:
      - "5000:5000"

  php-site:
    build:
      context: .
      dockerfile: site/Dockerfile
    container_name: php-site
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      - POSTGRES_HOST=${DB_HOST:-postgres}
      - POSTGRES_PORT=${DB_PORT:-5432}
      - POSTGRES_DATA_DB=${DB_DATABASE_DATA:-n8n_data}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
    volumes:
      - ./site:/var/www/html
    networks:
      - web
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - web
    depends_on:
      - postgres

networks:
  web:
    driver: bridge
volumes:
  traefik_data:
  postgres_data:
  n8n_data:
    external: true
    name: n8n_n8n_data
  pgadmin_data:
