services:
  traefik:
    image: 'traefik:latest'
    container_name: traefik
    restart: unless-stopped
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.mytlschallenge.acme.tlschallenge=true'
      - '--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}'
      - '--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'traefik_data:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - web
  postgres:
    image: pgvector/pgvector:pg15
    # build:
      # dockerfile: postgres/Dockerfile
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_DATABASE:-n8n}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER:-postgres}'
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.docker.network=web
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${SUBDOMAIN}.${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    environment:
      - DB_TYPE=${DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${DB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=${DB_PORT:-5432}
      - DB_POSTGRESDB_DATABASE=${DB_DATABASE:-n8n}
      - DB_POSTGRESDB_USER=${DB_USER:-postgres}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD:-changeme}
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
#      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_DATA_FOLDER=/home/node/.n8n
      - N8N_DEFAULT_CORS=true
      - N8N_CORS_ALLOWED_ORIGINS=https://receipt-insights-bot.vercel.app/
      - N8N_PROXY_HOPS=1
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168   # 7 дней
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
      - NODE_OPTIONS=--max-old-space-size=2048
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
      # - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      # - N8N_BLOCK_ENV_ACCESS_IN_EXPRESSIONS=false
      # - CENTRIFUGO_URL=${CENTRIFUGO_SUBDOMAIN}.${DOMAIN_NAME}
      # - CENTRIFUGO_API_KEY=CENTRIFUGO_API_KEY
      # - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - web
    depends_on:
      postgres:
        condition: service_healthy
      embedding-service:
        condition: service_started

  embedding-service:
    build: ./embedding-service
    container_name: embedding-service
    networks:
      - web
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1500M    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  centrifugo:
    build:
      context: ./centrifugo
      dockerfile: Dockerfile
    # image: centrifugo/centrifugo:latest
    container_name: centrifugo
    networks:
      - web # общая сеть с traefik
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.centrifugo.rule=Host(`${CENTRIFUGO_SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.centrifugo.entrypoints=websecure"
      - "traefik.http.routers.centrifugo.tls.certresolver=myresolver"
      - "traefik.http.services.centrifugo.loadbalancer.server.port=8000"

  php-site:
    build:
      context: .
      dockerfile: site/Dockerfile
    container_name: php-site
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      - POSTGRES_HOST=${DB_HOST:-postgres}
      - POSTGRES_PORT=${DB_PORT:-5432}
      - POSTGRES_DATA_DB=${DB_DATABASE_DATA:-n8n_data}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./site:/var/www/html
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.site.rule=Host(`${SITE_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.site.entrypoints=websecure
      - traefik.http.routers.site.tls=true
      - traefik.http.routers.site.tls.certresolver=mytlschallenge
      - traefik.http.services.site.loadbalancer.server.port=80
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - web
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`${PGA_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=mytlschallenge
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

networks:
  web:
    driver: bridge
volumes:
  traefik_data:
  postgres_data:
  n8n_data:
    external: true
    name: n8n_n8n_data
  pgadmin_data:
